# Generated by Django 5.0.6 on 2024-06-30 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yangilik yaratilgan vaqt'),
        ),
    ]
