# Generated by Django 5.1 on 2024-08-11 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'managed': True, 'ordering': ['-created_time'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelTable(
            name='commentmodel',
            table='Comments',
        ),
    ]
