# Generated by Django 5.1 on 2024-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_comment_commentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
