# Generated by Django 5.1 on 2024-08-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_hitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
