# Generated by Django 5.1 on 2024-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_delete_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name="Yangilik haqida ma'lumotlar"),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name="Yangilik haqida ma'lumotlar"),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name="Yangilik haqida ma'lumotlar"),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Yangilik nomi'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Yangilik nomi'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Yangilik nomi'),
        ),
    ]
