# Generated by Django 5.0.6 on 2024-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, default='images/1.jpeg', null=True, upload_to='account/'),
        ),
    ]
